<a href="https://colab.research.google.com/github/Chandu106/Multiclassification_Food101_project06/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Introduction to Tensors
 


In [ ]:
# import tensorflow

import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
# create tensors with tf.constants()

scalar = tf.constant(7)
scalar    

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor(ndim stands of dimensions)
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10 , 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimension of the vector
vector.ndim

1

In [ ]:
# create a matrix(has more than one dimension)
matrix = tf.constant([[10 , 7] , [7 , 10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create another matrix
another_matrix = tf.constant([[10. , 7.] , [3. , 2.] , [8. , 9.]], dtype=tf.float16) #specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# dimension of the another matrix
another_matrix.ndim

2

In [ ]:
from tensorflow.python.ops.gen_data_flow_ops import tensor_array
# lets create a tensor
tensor = tf.constant([[[1, 2 , 3],
                       [4 , 5 , 6],
                       [7 , 8 , 9],
                       [10 , 11 , 12],
                       [13, 14 , 15],
                       [16 , 17 , 18]]])
tensor 

<tf.Tensor: shape=(1, 6, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
# dimension of the tensor
tensor.ndim

3

In [ ]:
# create the same tensor with tf.variable()

changeable_tensor = tf.Variable([10 , 7])
unchangeable_tensor = tf.Variable([10 , 7])
changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# change one element in changeable tensor

changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# try using assign() in changeable tensor

changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# try using assign() in unchangeable tensor

unchangeable_tensor[0].assign(7)
unchangeable_tensor

 # creating random tensors

 

In [ ]:
# create two random (but the same) tensors

random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3 , 2))
random_2 = tf.random.Generator.from_seed(142) #set seed for reproducibility
random_2 = random_2.normal(shape=(3 , 2))
random_1 , random_2 , random_1 == random_2

In [ ]:
#shuffle the order of elements in a tensor

not_shuffled = tf.constant([[10 , 7],
                            [3 , 4],
                            [2 , 5]])

# shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

In [ ]:
not_shuffled

#converting numpy array to tensors

In [ ]:
import tensorflow as tf
tf.ones([10 , 7])

In [ ]:
tf.zeros([12 , 9])

In [ ]:
import numpy as np
numpy_A = np.arrange(1 , 25 , dtype=np.int32)
numpy_A

In [ ]:
# crearing a 2 dimensional tensor (rank of the tensor is 2)

In [ ]:
rank_2_tensor = tf.zeros(shape = (2 , 3))
rank_2_tensor

In [ ]:
rank_2_tensor = tf.constant([[10 , 7], [7 , 10]])
rank_2_tensor
rank_2_tensor.ndim
rank_2_tensor.shape
rank_2_tensor.dtype


#getting last item of each of row


In [ ]:
rank_2_tensor = tf.constant([[10 , 7], [7 , 10]])
rank_2_tensor[:,1]

In [ ]:
#matrix multiplication 

In [ ]:
import tensorflow as tf
x = tf.constant([[2,3],
                 [3,4]])
y = tf.constant([[1,2],
                 [5,6]])
x.shape , y.shape

In [ ]:
tf.matmul(x,y)

In [ ]:
x = tf.constant(shape = (2,3))
y = tf.constant(shape = (2,3))
x ,y

In [ ]:
#creating a x tensor with shape (2,3) and y tensor (2,3)

In [ ]:
x = tf.constant([[1,2,3],
                 [4,5,6]])
y = tf.constant([[3,2,1],
                 [9,8,7]])
tf.matmul(x,y)

In [ ]:
tf.reshape(y , shape = (2,3))


In [ ]:
import tensorflow as tf
c = tf.constant([1,2])
c.dtype

In [ ]:
d = tf.cast(c , dtype=tf.int16)
d.dtype

In [ ]:
import numpy as np
c = tf.constant(np.random.randint(0 , 100 , size = 50))
c 

In [ ]:
tf.size(c) , c.shape , c.ndim

In [ ]:
tf.reduce_min(c)
tf.reduce_max(c)

In [ ]:
tf.reduce_sum(c)

In [ ]:
from sklearn.model_selection import train_test_split
X1_train , X1_test , y_train , y_test = train_test_split(X1,
                                                       y,
                                                       test_size=0.2,
                                                       random_state=42)

In [ ]:
from sklearn.model_selection import train_test_split
X2_train , X2_test , y_train , y_test = train_test_split(X2,
                                                       y,
                                                       test_size=0.2,
                                                       random_state=42)

In [ ]:
# splitting our data as training and testing to train our model

from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,
                                                       y,
                                                       test_size=0.2,
                                                       random_state=42)

In [ ]:
X1 = project01["latitude"]
y = project01["temperature"]

In [ ]:
X2 = project01["altitude"]
y = project01["temperature"]